config/routes.rb
FirehoseQuiz::Application.routes.draw do

  root 'movements#index'

  resources :movements, :only => :create

end

app/models/movement.rb
class Movement < ActiveRecord::Base
	validates :movement_name, :presence => true, :length => { :minimum => 2 }
	validates :movement_category, :presence =>true

	MOVEMENT_CATEGORIES = [
		:weight,
		:gymnastics,
		:cardio
	]
end

app/models/workout.rb
class Workout < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
	def index
		@movements = Movement.all
		@movement = Movement.new
	end

	def create
		@movement = Movement.create(movement_params)
		if @movement.invalid?
			flash[:error] = 'You must enter a movement greater than 2 characters and a category!'
		end
		redirect_to root_path
	end

	private

	def movement_params
		params.require(:movement).permit(:movement_name, :movement_category)
	end

end

app/controllers/quiz_answers_controller.rb
class QuizAnswersController < ApplicationController
	def index
	end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/helpers/quiz_answers_helper.rb
module QuizAnswersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseQuiz</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class= "col-xs-11">
		<%= link_to '<h1>Quiz #2</h1>'.html_safe, root_path %>
		<% if flash[:error].present? %>
			<br />
			<div class="col-xs-10 col-xs-offset-1 alert alert-danger alert-dismissible">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<%= flash[:error].html_safe %>
			</div>
		<% end %>
	</div>
	
<%= yield %>

</body>
</html>

app/views/movements/index.html.erb
<div class= "col-xs-10 col-xs-offset-1">
<h2><u>Workout Movement List</u></h2>
<!-- Button trigger modal -->
<button class="btn btn-primary btn-med pull-left" data-toggle="modal" data-target="#myModal">
  Add movement
</button>
</div>
<div class="clear"></div>
<br />

<!-- Movement Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add a movement</h4>
      </div>
      <%= simple_form_for @movement, :url => movements_path do |f| %>
      	<div class="modal-body">
					<%= f.input :movement_name, :placeholder => 'Squat Clean' %> 
					<%= f.input :movement_category, :as => :select, :collection => Movement::MOVEMENT_CATEGORIES %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<%= f.submit "Add Movement", :class => 'btn btn-primary' %>
				</div>
			<% end %>
    </div>
  </div>
</div>

<div class= "col-xs-10 col-xs-offset-1">
<% @movements.each do |movement| %>
	<div class ="my-box">
		<h3 style="margin-bottom: 5px;"><%= movement.movement_name %></h3>
		<i><%= movement.movement_category %></i><br />
	</div>
<% end %>
</div>

app/views/quiz_answers/index.html.erb
<p>Here's some static content.</p>

app/views/workouts/index.html.erb
<h1>Workout List</h1>